import Head from 'next/head';

// * Components
import Navbar from '../components/UI/Navbar';
import Featured from '../components/Home/Sections/Featured';
import Latest from '../components/Home/Sections/Latest';

export default function Home() {
  return (
    <div className='w-full'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      {/* Home Page Content */}
      <div className='w-4/5 mx-auto'>
        <Featured />
        <Latest />
      </div>
      <footer>
        <p>Copyright</p>
      </footer>
    </div>
  );
}
